ALTER TABLE "User" ADD COLUMN "pushToken"     TEXT;
ALTER TABLE "User" ADD COLUMN "notifTraining" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "notifStreak"   BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "notifWeather"  BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "notifFriends"  BOOLEAN NOT NULL DEFAULT true;
